/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    public void LoginFrame() {
// ... code lainnya
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }
    
   
//code-code yang lain
    private void load_table() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("Id Transaksi");
        model.addColumn("Id Pasien");
        model.addColumn("Id Pegawai");
        model.addColumn("Kode Obat");
        model.addColumn("Nama Pasien");
        model.addColumn("Jumlah Obat");
        model.addColumn("Total Pembayaran");

        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "SELECT t.id_transaksi,p.id_pasien,i.id_pegawai,o.kode_obat,p.nama_lengkap_pasien,t.jumlah_obat,t.total_pembayaran FROM transaksi t, pasien p, obat o, pegawai i WHERE p.id_pasien = t.id_pasien AND o.kode_obat = t.kode_obat AND i.id_pegawai = t.id_pegawai;";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{ no++,res.getString(1), 
                    res.getString(2), res.getString(3), res.getString(4), res.getString(5)
                , res.getString(6), res.getString(7)});
            }
            table_transaksi.setModel(model);
        } catch (SQLException e) {
            System.out.println("ERROR" + e.getMessage());
        }
    }
    public Transaksi() {
        initComponents();
        load_table();
        KosongForm();
        LoginFrame();
        data_pegawai();
        data_obat();
        data_pasien();
    }
     public void KosongForm(){
        id_transaksi.setEditable(true);
        
        jumlah_obat.setText(null);
        total_pembayaran.setText(null);
    }
     public void data_pegawai(){
        
         try {
             String sql= "SELECT * FROM pegawai";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

             while (res.next()) {
                 combo_pegawai.addItem(res.getString("id_pegawai"));
             }

             res.last();
             int jumlahdata = res.getRow();
             res.first();
         } catch (SQLException e) {
         }
}
     public void data_obat(){
        
         try {
             String sql= "SELECT * FROM obat";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

             while (res.next()) {
                 combo_obat.addItem(res.getString("kode_obat"));
             }

             res.last();
             int jumlahdata = res.getRow();
             res.first();
         } catch (SQLException e) {
         }
}
     public void data_pasien(){
        
         try {
             String sql= "SELECT * FROM pasien";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

             while (res.next()) {
                 combo_pasien.addItem(res.getString("id_pasien"));
             }

             res.last();
             int jumlahdata = res.getRow();
             res.first();
         } catch (SQLException e) {
         }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_transaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JTextField();
        jumlah_obat = new javax.swing.JTextField();
        total_pembayaran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo_pegawai = new javax.swing.JComboBox<>();
        combo_obat = new javax.swing.JComboBox<>();
        combo_pasien = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        table_transaksi.setBackground(new java.awt.Color(153, 255, 204));
        table_transaksi.setForeground(new java.awt.Color(0, 0, 102));
        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_transaksi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(680, 70, 840, 510);

        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Id Transaksi");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 170, 87, 20);

        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Kode Obat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 290, 74, 20);

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Jumlah Obat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 330, 90, 20);

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Total Pembayaran");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 370, 128, 20);

        id_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(id_transaksi);
        id_transaksi.setBounds(260, 170, 400, 26);
        jPanel1.add(jumlah_obat);
        jumlah_obat.setBounds(260, 330, 400, 26);
        jPanel1.add(total_pembayaran);
        total_pembayaran.setBounds(260, 370, 400, 26);

        jButton1.setText("Kembali Ke Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 550, 153, 29);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("DATA TRANSAKSI");
        jLabel5.setMaximumSize(new java.awt.Dimension(274, 41));
        jLabel5.setMinimumSize(new java.awt.Dimension(274, 41));
        jLabel5.setPreferredSize(new java.awt.Dimension(274, 41));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 100, 240, 28);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar);
        btn_keluar.setBounds(510, 410, 77, 29);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal);
        btn_batal.setBounds(600, 410, 67, 29);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus);
        btn_hapus.setBounds(420, 410, 77, 29);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(340, 410, 59, 29);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan);
        btn_simpan.setBounds(240, 410, 85, 29);

        jButton2.setText("Cetak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(140, 410, 93, 29);

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Id Pegawai");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 210, 78, 20);

        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Id Pasien");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 250, 65, 20);

        jPanel1.add(combo_pegawai);
        combo_pegawai.setBounds(260, 210, 120, 26);

        jPanel1.add(combo_obat);
        combo_obat.setBounds(260, 290, 120, 26);

        jPanel1.add(combo_pasien);
        combo_pasien.setBounds(260, 250, 120, 26);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view2/desain_all.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1, 0, 1550, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_transaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO transaksi VALUES ('"+id_transaksi.getText()+"',"
                    +"'"+combo_pegawai.getSelectedItem()+"',"
                   
                    +"'"+combo_pasien.getSelectedItem()+"',"
                    +"'"+combo_obat.getSelectedItem()+"',"
                    +"'"+jumlah_obat.getText()+"',"
                    +"'"+total_pembayaran.getText()+"')";
            
                   
                    
                    
                   
            
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE transaksi SET id_transaksi = '"+id_transaksi.getText()
                    +"', id_pasien= '"+combo_pasien.getSelectedItem()
                    +"', id_pegawai= '"+combo_pegawai.getSelectedItem()
                    +"', kode_obat = '"+combo_obat.getSelectedItem()
                    +"', jumlah_obat = '"+jumlah_obat.getText()
                    +"', total_pembayaran = '"+total_pembayaran.getText()
                    +"'WHERE id_transaksi = '"+id_transaksi.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
    }//GEN-LAST:event_btn_editActionPerformed

    private void table_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_transaksiMouseClicked
        // TODO add your handling code here:
        int baris = table_transaksi.rowAtPoint(evt.getPoint());
        
        String id = table_transaksi.getValueAt(baris,1).toString();
        id_transaksi.setText(id);
        String pegwai = table_transaksi.getValueAt(baris,3).toString();
        combo_pegawai.setSelectedItem(pegwai);
        String pasien = table_transaksi.getValueAt(baris,2).toString();
        combo_pasien.setSelectedItem(pasien);
        String obat = table_transaksi.getValueAt(baris,4).toString();
        combo_obat.setSelectedItem(obat);
        String jml = table_transaksi.getValueAt(baris,6).toString();
        jumlah_obat.setText(jml);
        String total =table_transaksi.getValueAt(baris, 7).toString();
        total_pembayaran.setText(total);
    }//GEN-LAST:event_table_transaksiMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from transaksi where id_transaksi ='"+id_transaksi.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        KosongForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            InputStream is  =  Transaksi.class.getResourceAsStream("/Laporan/Transaksi.jasper");
            JasperPrint jsPrint = JasperFillManager.fillReport(is, null, config.configDB());
            JasperViewer.viewReport(jsPrint, false);     
        }
        catch (Exception e){ 
            JOptionPane.showMessageDialog(null, "Gagal mencetak karena : "
                    + e.getMessage(), "Cetak Laporan", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Linux".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> combo_obat;
    private javax.swing.JComboBox<String> combo_pasien;
    private javax.swing.JComboBox<String> combo_pegawai;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_obat;
    private javax.swing.JTable table_transaksi;
    private javax.swing.JTextField total_pembayaran;
    // End of variables declaration//GEN-END:variables
}
